# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Contact | Kapil"
description:        ""

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                ""
author:             "sirkapil"
twitter:
  username:         "kapil_rc"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            "https://contact.heykapil.in"
#baseurl:            "" #For Root Domain
permalink:          /:title/

# Markdown
markdown:           kramdown

# MathJax
mathjax: false

#Background
bg: red

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "page"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


exclude: 
      ["_dev",
      "gulpfile.js",    
      "node_modules",
      "package.json"]


markdown: kramdown
compress_html:
       clippings:      all
       comments:       ["<!-- ", " -->"]
       endings:        all 
       ignore: 
             envs:     [development]
       startings:      [html, head, body]
